const SPLASH_SCREEN = "SPLASH_SCREEN";
const SIGNUP_SCREEN = "SIGNUP_SCREEN";
const LOGIN_SCREEN = "LOGIN_SCREEN";
const FORGOT_PASSWORD_SCREEN = "FORGOT_PASSWORD_SCREEN";
const MOBILE_VERIFICATION_SCREEN = "MOBILE_VERIFICATION_SCREEN";
