import 'dart:ui';

import 'package:flutter/material.dart';

Map<String, TextStyle> blackTextStyles = {
  '14_normal': TextStyle(fontSize: 14, color: Colors.black, fontWeight: FontWeight.normal),
  '14_bold': TextStyle(fontSize: 14, color: Colors.black, fontWeight: FontWeight.bold),
  '16_normal': TextStyle(fontSize: 16, color: Colors.black, fontWeight: FontWeight.normal),
  '16_bold': TextStyle(fontSize: 16, color: Colors.black, fontWeight: FontWeight.bold),
  '18_normal': TextStyle(fontSize: 18, color: Colors.black, fontWeight: FontWeight.normal),
  '18_bold': TextStyle(fontSize: 18, color: Colors.black, fontWeight: FontWeight.bold),
  '20_normal': TextStyle(fontSize: 20, color: Colors.black, fontWeight: FontWeight.normal),
  '20_bold': TextStyle(fontSize: 20, color: Colors.black, fontWeight: FontWeight.bold),
  '22_normal': TextStyle(fontSize: 22, color: Colors.black, fontWeight: FontWeight.normal),
  '22_bold': TextStyle(fontSize: 22, color: Colors.black, fontWeight: FontWeight.bold),
  '24_normal': TextStyle(fontSize: 24, color: Colors.black, fontWeight: FontWeight.normal),
  '24_bold': TextStyle(fontSize: 24, color: Colors.black, fontWeight: FontWeight.bold),
  '26_normal': TextStyle(fontSize: 26, color: Colors.black, fontWeight: FontWeight.normal),
  '26_bold': TextStyle(fontSize: 26, color: Colors.black, fontWeight: FontWeight.bold),
  '28_normal': TextStyle(fontSize: 28, color: Colors.black, fontWeight: FontWeight.normal),
  '28_bold': TextStyle(fontSize: 28, color: Colors.black, fontWeight: FontWeight.bold),
  '30_normal': TextStyle(fontSize: 30, color: Colors.black, fontWeight: FontWeight.normal),
  '30_bold': TextStyle(fontSize: 30, color: Colors.black, fontWeight: FontWeight.bold),
  '32_normal': TextStyle(fontSize: 32, color: Colors.black, fontWeight: FontWeight.normal),
  '32_bold': TextStyle(fontSize: 32, color: Colors.black, fontWeight: FontWeight.bold),
  '34_normal': TextStyle(fontSize: 34, color: Colors.black, fontWeight: FontWeight.normal),
  '34_bold': TextStyle(fontSize: 34, color: Colors.black, fontWeight: FontWeight.bold),
};

Map<String, TextStyle> whiteTextStyles = {
  '14_normal': TextStyle(fontSize: 14, color: Colors.white, fontWeight: FontWeight.normal),
  '14_bold': TextStyle(fontSize: 14, color: Colors.white, fontWeight: FontWeight.bold),
  '16_normal': TextStyle(fontSize: 16, color: Colors.white, fontWeight: FontWeight.normal),
  '16_bold': TextStyle(fontSize: 16, color: Colors.white, fontWeight: FontWeight.bold),
  '18_normal': TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.normal),
  '18_bold': TextStyle(fontSize: 18, color: Colors.white, fontWeight: FontWeight.bold),
  '20_normal': TextStyle(fontSize: 20, color: Colors.white, fontWeight: FontWeight.normal),
  '20_bold': TextStyle(fontSize: 20, color: Colors.white, fontWeight: FontWeight.bold),
  '22_normal': TextStyle(fontSize: 22, color: Colors.white, fontWeight: FontWeight.normal),
  '22_bold': TextStyle(fontSize: 22, color: Colors.white, fontWeight: FontWeight.bold),
  '24_normal': TextStyle(fontSize: 24, color: Colors.white, fontWeight: FontWeight.normal),
  '24_bold': TextStyle(fontSize: 24, color: Colors.white, fontWeight: FontWeight.bold),
  '26_normal': TextStyle(fontSize: 26, color: Colors.white, fontWeight: FontWeight.normal),
  '26_bold': TextStyle(fontSize: 26, color: Colors.white, fontWeight: FontWeight.bold),
  '28_normal': TextStyle(fontSize: 28, color: Colors.white, fontWeight: FontWeight.normal),
  '28_bold': TextStyle(fontSize: 28, color: Colors.white, fontWeight: FontWeight.bold),
  '30_normal': TextStyle(fontSize: 30, color: Colors.white, fontWeight: FontWeight.normal),
  '30_bold': TextStyle(fontSize: 30, color: Colors.white, fontWeight: FontWeight.bold),
  '32_normal': TextStyle(fontSize: 32, color: Colors.white, fontWeight: FontWeight.normal),
  '32_bold': TextStyle(fontSize: 32, color: Colors.white, fontWeight: FontWeight.bold),
  '34_normal': TextStyle(fontSize: 34, color: Colors.white, fontWeight: FontWeight.normal),
  '34_bold': TextStyle(fontSize: 34, color: Colors.white, fontWeight: FontWeight.bold),
  '36_normal': TextStyle(fontSize: 36, color: Colors.white, fontWeight: FontWeight.normal),
  '36_bold': TextStyle(fontSize: 36, color: Colors.white, fontWeight: FontWeight.bold),
  '38_normal': TextStyle(fontSize: 38, color: Colors.white, fontWeight: FontWeight.normal),
  '38_bold': TextStyle(fontSize: 38, color: Colors.white, fontWeight: FontWeight.bold),
  '40_normal': TextStyle(fontSize: 40, color: Colors.white, fontWeight: FontWeight.normal),
  '40_bold': TextStyle(fontSize: 40, color: Colors.white, fontWeight: FontWeight.bold),
};

Map<String, TextStyle> primaryTextStyles = {
  '14_normal': TextStyle(fontSize: 14, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '14_bold': TextStyle(fontSize: 14, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '16_normal': TextStyle(fontSize: 16, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '16_bold': TextStyle(fontSize: 16, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '18_normal': TextStyle(fontSize: 18, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '18_bold': TextStyle(fontSize: 18, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '20_normal': TextStyle(fontSize: 20, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '20_bold': TextStyle(fontSize: 20, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '22_normal': TextStyle(fontSize: 22, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '22_bold': TextStyle(fontSize: 22, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '24_normal': TextStyle(fontSize: 24, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '24_bold': TextStyle(fontSize: 24, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '26_normal': TextStyle(fontSize: 26, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '26_bold': TextStyle(fontSize: 26, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '28_normal': TextStyle(fontSize: 28, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '28_bold': TextStyle(fontSize: 28, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '30_normal': TextStyle(fontSize: 30, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '30_bold': TextStyle(fontSize: 30, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '32_normal': TextStyle(fontSize: 32, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '32_bold': TextStyle(fontSize: 32, color: Colors.deepOrange, fontWeight: FontWeight.bold),
  '34_normal': TextStyle(fontSize: 34, color: Colors.deepOrange, fontWeight: FontWeight.normal),
  '34_bold': TextStyle(fontSize: 34, color: Colors.deepOrange, fontWeight: FontWeight.bold),
};

TextStyle errorText = TextStyle(color:  Colors.red , fontSize: 16);